version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}     
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}     
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD} 
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}     
    volumes:
      - ~/efs:/var/www/html  
    restart: always

volumes:
  efs:

